### ISSUE TITLE
New version of app marked as outdated

### ISSUE THREAD

**Issue by itsliamdowd** [manasv/Updeto#2]
Hello, the new version of the app (example: version 2.0 when 1.0 is on the app store) is marked as outdated. Can this be fixed?

**Comment by manasv** [comment]
Hey, 
Thank you for this feedback.

Haven't touched source code for `Updeto` in a while, this may be a good time for a little maintenance here.

Essentially I think I haven't communicated well what the library does right now, and your example is valid for start making some improvements.

If you inspect the source code right now, you will find that what the Library does, is just comparing if the provided version (or the one contained in the Bundle) is equal to the one Appstore has, and if it's different it will show outdated.

Our unique source of truth is the AppStore, if the AppStore says latest is 1.0.0 and you have 2.0.0, you may have a development / TestFlight build.

I will try to put some mind to some solution even if this doesn't look like a recurrent use case, I may give a try to a more deep comparison instead of a plain string comparison.

**Comment by itsliamdowd** [comment]
I think I might have found a fix check my recent pull request to see if it works

**Comment by manasv** [comment]
Hey, sorry for the super delayed response to this.

I did see your pull request (#4) and was surprised by how easy it was to compare version strings, but I'm trying to implement a feature that is more aligned with what is currently happening and bringing another "Result" that can be handled.

Basically added a better comparison method, and added a new case `.developmentOrBeta`.

The library purpose is to be based on the response from Apple API, if your installed version is higher there are just 3 possibilities.

1) You are using a version compiled from Xcode and with higher version number
2) You are using a version from TestFlight or other beta distribution platform with higher version number
3) Apple API is outdated (Unlikely)

And also to remember that in real use the library will produce no results if using an invalid bundleId, a.k.a your app doesn't have any version published into the AppStore.

But still, if you don't want to do anything with the `.developmentOrBeta` result you can still do something like:

```swift
switch result {
case .updated, .developmentOrBeta:
    break
case .outdated:
    break
case .noResults:
    break
}
```

Just in case you want to handle that the same as you handle updated.

In any case will leave the issue open if you bring any discussion, if not I will close it in the following days.

Thank you for finding the bug and the contribution.
